"""
Build stocks_to_fetch.json from Nifty 500 constituents + Dhan security master.

This script:
1. Reads nifty500_constituents.json (list of 500 symbols)
2. Queries Dhan API security master for security_ids
3. Generates config/stocks_to_fetch.json with all 500 stocks
4. Marks high-performers as enabled, others as data-collection-only

Usage:
    python -m app.build_stocks_config

Environment Requirements:
    - DHAN_CLIENT_ID
    - DHAN_ACCESS_TOKEN
"""

import json
import logging
from pathlib import Path
from .dhan_client import DhanClient

LOG = logging.getLogger(__name__)

NIFTY500_FILE = Path(__file__).parent / "data" / "nifty500_constituents.json"
CONFIG_OUTPUT = Path(__file__).parent.parent / "config" / "stocks_to_fetch.json"

# Phase 1 high-performers (enable these)
HIGH_PERFORMERS = {
    "AXISBANK": "Phase 1 BUY signal generator - 1.43% pass rate (21 setups, primary source)",
    "BAJFINANCE": "Phase 1 BUY signal generator - 0.54% pass rate (8 setups)",
    "AUBANK": "Phase 1 BUY signal generator - 0.20% pass rate (3 setups)",
}


def load_nifty500_symbols():
    """Load Nifty 500 symbols from JSON file."""
    try:
        with open(NIFTY500_FILE) as f:
            data = json.load(f)
        symbols = data.get("symbols", [])
        print(f"[OK] Loaded {len(symbols)} Nifty 500 symbols from {NIFTY500_FILE}")
        return symbols
    except Exception as e:
        print(f"[ERROR] Failed to load Nifty 500 file: {e}")
        return None


def get_security_ids(symbols):
    """Query Dhan API for security IDs."""
    try:
        print("\n[DHAN API] Fetching security master...")
        dhan = DhanClient()
        symbol_map = dhan.build_symbol_map(symbols)
        print(f"[OK] Matched {len(symbol_map)}/{len(symbols)} symbols with Dhan security IDs")
        return symbol_map
    except Exception as e:
        print(f"[ERROR] Failed to query Dhan API: {e}")
        return None


def generate_config(symbols, security_map):
    """Generate stocks_to_fetch.json config."""
    stocks = []

    for symbol in sorted(symbols):
        if symbol not in security_map:
            print(f"  [WARN] Skipping {symbol} - no security ID found")
            continue

        security_id = security_map[symbol]["security_id"]

        # Check if high-performer
        if symbol in HIGH_PERFORMERS:
            enabled = True
            reason = HIGH_PERFORMERS[symbol]
        else:
            enabled = False
            reason = "Data collection only - not in Phase 1 signal generators"

        stocks.append({
            "symbol": symbol,
            "security_id": int(security_id),
            "enabled": enabled,
            "reason": reason,
        })

    config = {
        "fetch_config": {
            "description": "Nifty 500 stocks for historical data fetching. Phase 1 uses top 3 BUY performers.",
            "note": "Security IDs obtained from Dhan API security master. Auto-generated by build_stocks_config.py",
            "stocks": stocks,
            "parameters": {
                "interval_minutes": 15,
                "days_back": 90,
                "output_format": "csv",
                "append_to_existing": True,
            },
        }
    }

    return config


def main():
    """Main: build and save config."""
    print("\n" + "="*90)
    print("BUILD: stocks_to_fetch.json from Nifty 500 + Dhan Security Master")
    print("="*90)

    # Load Nifty 500 symbols
    symbols = load_nifty500_symbols()
    if not symbols:
        return False

    # Get security IDs from Dhan
    security_map = get_security_ids(symbols)
    if not security_map:
        return False

    # Generate config
    print("\n[CONFIG] Generating configuration...")
    config = generate_config(symbols, security_map)

    matched_count = len(config["fetch_config"]["stocks"])
    enabled_count = len([s for s in config["fetch_config"]["stocks"] if s["enabled"]])

    print(f"[OK] Total stocks: {matched_count}")
    print(f"  - Enabled (Phase 1): {enabled_count}")
    print(f"  - Data collection only: {matched_count - enabled_count}")

    # Save config
    try:
        CONFIG_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        with open(CONFIG_OUTPUT, "w") as f:
            json.dump(config, f, indent=2)
        print(f"\n[OK] Config saved: {CONFIG_OUTPUT}")
    except Exception as e:
        print(f"\n[ERROR] Failed to save config: {e}")
        return False

    # Summary
    print(f"\n[SUMMARY]")
    print(f"  Total Nifty 500: {len(symbols)}")
    print(f"  Matched with Dhan: {matched_count}")
    print(f"  Phase 1 enabled: {enabled_count}")
    print(f"\n[NEXT]")
    print(f"  Run: python -m app.job_fetch_historical_data")
    print(f"  This will fetch 90-day data for all {matched_count} stocks")

    return True


if __name__ == "__main__":
    import sys
    success = main()
    sys.exit(0 if success else 1)
